---
title: "eda.Rmd"
author: "Brian Detweiler"
date: "December 25, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 4, fig.width = 4, fig.align = 'center')
```

## R Markdown

```{r, cache=TRUE}
# setwd('/home/bdetweiler/src/Data_Science/stat-8960-capstone-project')

library("devtools")
library('MonetDBLite')
library('MonetDB.R')
library('dplyr')
library('dbplyr')
library('DBI')

```


```{r, warning=FALSE}
# MonetDB connection to a permanent file
# Call the below line if you get an error about connecting
MonetDBLite::monetdblite_shutdown()
mdb <- DBI::dbConnect(MonetDBLite::MonetDBLite(), "data")
mdb <- dbConnect(MonetDBLite::MonetDBLite(), "data")
?dbConnect
nis <- read.csv("data/NIS2001.csv", stringsAsFactors=FALSE)
create <- "CREATE TABLE nis (\"KEY\" DOUBLE PRECISION,
                  \"YEAR\" STRING,
                  \"AGE\" STRING,
                  \"AMONTH\" STRING,
                  \"AQTR\" STRING,
                  \"ASEASON\" STRING,
                  \"ASOURCE\" STRING,
                  \"ATYPE\" STRING,
                  \"AWEEKEND\" STRING,
                  \"DIED\" STRING,
                  \"DQTR\" STRING,
                  \"DRG\" STRING,
                  \"DX1\" STRING,
                  \"DX2\" STRING,
                  \"DX3\" STRING,
                  \"DX4\" STRING,
                  \"DX5\" STRING,
                  \"DX6\" STRING,
                  \"DX7\" STRING,
                  \"DX8\" STRING,
                  \"DX9\" STRING,
                  \"DX10\" STRING,
                  \"DX11\" STRING,
                  \"DX12\" STRING,
                  \"DX13\" STRING,
                  \"DX14\" STRING,
                  \"DX15\" STRING,
                  \"DXCCS1\" STRING,
                  \"DXCCS2\" STRING,
                  \"DXCCS3\" STRING,
                  \"DXCCS4\" STRING,
                  \"DXCCS5\" STRING,
                  \"DXCCS6\" STRING,
                  \"DXCCS7\" STRING,
                  \"DXCCS8\" STRING,
                  \"DXCCS9\" STRING,
                  \"DXCCS10\" STRING,
                  \"DXCCS11\" STRING,
                  \"DXCCS12\" STRING,
                  \"DXCCS13\" STRING,
                  \"DXCCS14\" STRING,
                  \"DXCCS15\" STRING,
                  \"PR1\" STRING,
                  \"PR2\" STRING,
                  \"PR3\" STRING,
                  \"PR4\" STRING,
                  \"PR5\" STRING,
                  \"PR6\" STRING,
                  \"PR7\" STRING,
                  \"PR8\" STRING,
                  \"PR9\" STRING,
                  \"PR10\" STRING,
                  \"PR11\" STRING,
                  \"PR12\" STRING,
                  \"PR13\" STRING,
                  \"PR14\" STRING,
                  \"PR15\" STRING,
                  \"PRDAY1\" STRING,
                  \"PRDAY2\" STRING,
                  \"PRDAY3\" STRING,
                  \"PRDAY4\" STRING,
                  \"PRDAY5\" STRING,
                  \"PRDAY6\" STRING,
                  \"PRDAY7\" STRING,
                  \"PRDAY8\" STRING,
                  \"PRDAY9\" STRING,
                  \"PRDAY10\" STRING,
                  \"PRDAY11\" STRING,
                  \"PRDAY12\" STRING,
                  \"PRDAY13\" STRING,
                  \"PRDAY14\" STRING,
                  \"PRDAY15\" STRING,
                  \"PRCCS1\" STRING,
                  \"PRCCS2\" STRING,
                  \"PRCCS3\" STRING,
                  \"PRCCS4\" STRING,
                  \"PRCCS5\" STRING,
                  \"PRCCS6\" STRING,
                  \"PRCCS7\" STRING,
                  \"PRCCS8\" STRING,
                  \"PRCCS9\" STRING,
                  \"PRCCS10\" STRING,
                  \"PRCCS11\" STRING,
                  \"PRCCS12\" STRING,
                  \"PRCCS13\" STRING,
                  \"PRCCS14\" STRING,
                  \"PRCCS15\" STRING,
                  \"DISPUNIFORM\" STRING,
                  \"FEMALE\" STRING,
                  \"LOS\" STRING,
                  \"MDC\" STRING,
                  \"NDX\" STRING,
                  \"PAY1\" STRING,
                  \"RACE\" STRING,
                  \"TOTCHG\" STRING,
                  \"ZIPINC_QRTL\" STRING,
                  \"NIS_STRATUM\" STRING,
                  \"NPR\" STRING,
                  \"CHF\" STRING,
                  \"VALVE\" STRING,
                  \"PULMCIRC\" STRING,
                  \"PERIVASC\" STRING,
                  \"HTN_C\" STRING,
                  \"PARA\" STRING,
                  \"NEURO\" STRING,
                  \"CHRNLUNG\" STRING,
                  \"DM\" STRING,
                  \"DMCX\" STRING,
                  \"HYPOTHY\" STRING,
                  \"RENLFAIL\" STRING,
                  \"LIVER\" STRING,
                  \"ULCER\" STRING,
                  \"AIDS\" STRING,
                  \"LYMPH\" STRING,
                  \"METS\" STRING,
                  \"TUMOR\" STRING,
                  \"ARTH\" STRING,
                  \"COAG\" STRING,
                  \"OBESE\" STRING,
                  \"WGHTLOSS\" STRING,
                  \"LYTES\" STRING,
                  \"BLDLOSS\" STRING,
                  \"ANEMDEF\" STRING,
                  \"ALCOHOL\" STRING,
                  \"DRUG\" STRING,
                  \"PSYCH\" STRING,
                  \"DEPRESS\" STRING,
                  \"HOSPID\" STRING,
                  \"HOSPNAME\" STRING,
                  \"HOSPADDR\" STRING,
                  \"HOSPSTCO\" STRING,
                  \"HOSPST\" STRING,
                  \"HOSPCITY\" STRING,
                  \"HOSPZIP\" STRING,
                  \"HOSPWT\" STRING,
                  \"DISCWT\" DOUBLE PRECISION,
                  \"HOSP_BEDSIZE\" STRING,
                  \"HOSP_CONTROL\" INTEGER,
                  \"HOSP_LOCTEACH\" INTEGER,
                  \"HOSP_REGION\" INTEGER,
                  \"HOSP_LOCATION\" INTEGER,
                  \"HOSP_TEACH\" INTEGER,
                  \"N_DISC_U\" INTEGER,
                  \"N_HOSP_U\" INTEGER,
                  \"S_DISC_U\" INTEGER,
                  \"S_HOSP_U\" INTEGER,
                  \"TOTAL_DISC\" INTEGER,
                  \"WAGEINDEX\" DOUBLE PRECISION,
                  \"CCR_NIS\" DOUBLE PRECISION )"
print(create)
dbSendQuery(mdb, create)
dbSendQuery(mdb, "SELECT * FROM")
dbSendQuery(mdb, "COPY OFFSET 2
                  INTO nis
                  FROM '/home/bdetweiler/src/Data_Science/stat-8960-capstone-project/data/NIS2001.csv' USING  DELIMITERS ','")
```
