---
title: "eda.Rmd"
author: "Brian Detweiler"
date: "December 25, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 4, fig.width = 4, fig.align = 'center')
```

## R Markdown

```{r, cache=TRUE}
# setwd('/home/bdetweiler/src/Data_Science/stat-8960-capstone-project')

library("devtools")
library('MonetDB.R')
#install.packages('MonetDBLite')
library('MonetDBLite')
library('dplyr')
library('dbplyr')
library('DBI')
library('ggplot2')
library('scales')
```


```{r, warning=FALSE}
# MonetDB connection to a permanent file
# Call the below line if you get an error about connecting
# MonetDBLite::monetdblite_shutdown()
con <- DBI::dbConnect(MonetDBLite::MonetDBLite(), "data/nis_db")

q <- DBI::dbGetQuery(con, "SELECT *
                             FROM nrd
                            WHERE nrd_visitlink in (SELECT nrd_visitlink
                                                      FROM nrd 
                                                     WHERE dx1      = '00845' OR 
                                                           dx2      = '00845' OR
                                                           dx3      = '00845' OR
                                                           dx4      = '00845' OR
                                                           dx5      = '00845' OR
                                                           dx6      = '00845' OR
                                                           dx7      = '00845' OR
                                                           dx8      = '00845' OR
                                                           dx9      = '00845' OR
                                                           dx10     = '00845' OR
                                                           dx11     = '00845' OR
                                                           dx12     = '00845' OR
                                                           dx13     = '00845' OR
                                                           dx14     = '00845' OR
                                                           dx15     = '00845' OR
                                                           dx16     = '00845' OR
                                                           dx17     = '00845' OR
                                                           dx18     = '00845' OR
                                                           dx19     = '00845' OR
                                                           dx20     = '00845' OR
                                                           dx21     = '00845' OR
                                                           dx22     = '00845' OR
                                                           dx23     = '00845' OR
                                                           dx24     = '00845' OR
                                                           dx25     = '00845' OR
                                                           dx26     = '00845' OR
                                                           dx27     = '00845' OR
                                                           dx28     = '00845' OR
                                                           dx29     = '00845' OR
                                                           dx30     = '00845' OR
                                                           i10_dx1  = 'A047'  OR
                                                           i10_dx2  = 'A047'  OR
                                                           i10_dx3  = 'A047'  OR
                                                           i10_dx4  = 'A047'  OR
                                                           i10_dx5  = 'A047'  OR
                                                           i10_dx6  = 'A047'  OR
                                                           i10_dx7  = 'A047'  OR
                                                           i10_dx8  = 'A047'  OR
                                                           i10_dx9  = 'A047'  OR
                                                           i10_dx10 = 'A047'  OR
                                                           i10_dx11 = 'A047'  OR
                                                           i10_dx12 = 'A047'  OR
                                                           i10_dx13 = 'A047'  OR
                                                           i10_dx14 = 'A047'  OR
                                                           i10_dx15 = 'A047'  OR
                                                           i10_dx16 = 'A047'  OR
                                                           i10_dx17 = 'A047'  OR
                                                           i10_dx18 = 'A047'  OR
                                                           i10_dx19 = 'A047'  OR
                                                           i10_dx20 = 'A047'  OR
                                                           i10_dx21 = 'A047'  OR
                                                           i10_dx22 = 'A047'  OR
                                                           i10_dx23 = 'A047'  OR
                                                           i10_dx24 = 'A047'  OR
                                                           i10_dx25 = 'A047'  OR
                                                           i10_dx26 = 'A047'  OR
                                                           i10_dx27 = 'A047'  OR
                                                           i10_dx28 = 'A047'  OR
                                                           i10_dx29 = 'A047'  OR
                                                           i10_dx30 = 'A047')")
write.csv(q, 'data/cdiff-nrd.csv', row.names = FALSE)
```