\begin{abstract}
Clostridium Difficile Infection (C. \textit{diff} Infection, or simply CDI) 
is a highly contagious endospore forming bacterium that is transferred
through physical contact with an infected surface. Symptoms range from diarrhea to
life-threatening colitis. Elderly patients in hospitals and nursing homes receiving antimicrobial
treatment are at the highest risk of infection, and roughly one in nine patients over 65 will
die within 30 days of diagnosis. In this paper, we seek to model the risk of contracting CDI in both
hospital and nursing home settings given patient-to-patient or patient-to-healthcare provider 
contact. We then provide recommendations for minimizing the risk and controlling the spread of CDI.
\end{abstract}